gMapSecName_PalletTown::
	.string "Pallet Town$"

gMapSecName_ViridianCity::
	.string "Viridian City$"

gMapSecName_PewterCity::
	.string "Pewter City$"

gMapSecName_CeruleanCity::
	.string "Cerulean City$"

gMapSecName_LavenderTown::
	.string "Lavender Town$"

gMapSecName_VermilionCity::
	.string "Vermilion City$"

gMapSecName_CeladonCity::
	.string "Celadon City$"

gMapSecName_FuchsiaCity::
	.string "Fuchsia City$"

gMapSecName_CinnabarIsland::
	.string "Cinnabar Island$"

gMapSecName_IndigoPlateau::
	.string "Indigo Plateau$"

gMapSecName_SaffronCity::
	.string "Saffron City$"

gMapSecName_Route4::
	.string "Route 4$"

gMapSecName_Route10::
	.string "Route 10$"

gMapSecName_Route1::
	.string "Route 1$"

gMapSecName_Route2::
	.string "Route 2$"

gMapSecName_Route3::
	.string "Route 3$"

gMapSecName_Route4_2::
	.string "Route 4$"

gMapSecName_Route5::
	.string "Route 5$"

gMapSecName_Route6::
	.string "Route 6$"

gMapSecName_Route7::
	.string "Route 7$"

gMapSecName_Route8::
	.string "Route 8$"

gMapSecName_Route9::
	.string "Route 9$"

gMapSecName_Route10_2::
	.string "Route 10$"

gMapSecName_Route11::
	.string "Route 11$"

gMapSecName_Route12::
	.string "Route 12$"

gMapSecName_Route13::
	.string "Route 13$"

gMapSecName_Route14::
	.string "Route 14$"

gMapSecName_Route15::
	.string "Route 15$"

gMapSecName_Route16::
	.string "Route 16$"

gMapSecName_Route17::
	.string "Route 17$"

gMapSecName_Route18::
	.string "Route 18$"

gMapSecName_Route19::
	.string "Route 19$"

gMapSecName_Route20::
	.string "Route 20$"

gMapSecName_Route21::
	.string "Route 21$"

gMapSecName_Route22::
	.string "Route 22$"

gMapSecName_Route23::
	.string "Route 23$"

gMapSecName_Route24::
	.string "Route 24$"

gMapSecName_Route25::
	.string "Route 25$"

gMapSecName_ViridianForest::
	.string "Viridian Forest$"

gMapSecName_MtMoon::
	.string "Mt. Moon$"

gMapSecName_SSAnne::
	.string "S.S. Anne$"

gMapSecName_UndergroundPath::
	.string "Underground Path$"

gMapSecName_UndergroundPath_2::
	.string "Underground Path$"

gMapSecName_DiglettsCave::
	.string "Diglett's Cave$"

gMapSecName_VictoryRoad::
	.string "Victory Road$"

gMapSecName_RocketHideout::
	.string "Rocket Hideout$"

gMapSecName_SilphCo::
	.string "Silph Co.$"

gMapSecName_PokemonMansion::
	.string "Pokémon Mansion$"

gMapSecName_SafariZone::
	.string "Safari Zone$"

gMapSecName_PokemonLeague::
	.string "Pokémon League$"

gMapSecName_RockTunnel::
	.string "Rock Tunnel$"

gMapSecName_SeafoamIslands::
	.string "Seafoam Islands$"

gMapSecName_PokemonTower::
	.string "Pokémon Tower$"

gMapSecName_CeruleanCave::
	.string "Cerulean Cave$"

gMapSecName_PowerPlant::
	.string "Power Plant$"

gMapSecName_OneIsland::
	.string "One Island$"

gMapSecName_TwoIsland::
	.string "Two Island$"

gMapSecName_ThreeIsland::
	.string "Three Island$"

gMapSecName_FourIsland::
	.string "Four Island$"

gMapSecName_FiveIsland::
	.string "Five Island$"

gMapSecName_SixIsland::
	.string "Six Island$"

gMapSecName_SevenIsland::
	.string "Seven Island$"

gMapSecName_KindleRoad::
	.string "Kindle Road$"

gMapSecName_TreasureBeach::
	.string "Treasure Beach$"

gMapSecName_CapeBrink::
	.string "Cape Brink$"

gMapSecName_BondBridge::
	.string "Bond Bridge$"

gMapSecName_ThreeIslePort::
	.string "Three Isle Port$"

gMapSecName_SeviiIsle6::
	.string "Sevii Isle 6$"

gMapSecName_SeviiIsle7::
	.string "Sevii Isle 7$"

gMapSecName_SeviiIsle8::
	.string "Sevii Isle 8$"

gMapSecName_SeviiIsle9::
	.string "Sevii Isle 9$"

gMapSecName_ResortGorgeous::
	.string "Resort Gorgeous$"

gMapSecName_WaterLabyrinth::
	.string "Water Labyrinth$"

gMapSecName_FiveIsleMeadow::
	.string "Five Isle Meadow$"

gMapSecName_MemorialPillar::
	.string "Memorial Pillar$"

gMapSecName_OutcastIsland::
	.string "Outcast Island$"

gMapSecName_GreenPath::
	.string "Green Path$"

gMapSecName_WaterPath::
	.string "Water Path$"

gMapSecName_RuinValley::
	.string "Ruin Valley$"

gMapSecName_TrainerTower::
	.string "Trainer Tower$"

gMapSecName_CanyonEntrance::
	.string "Canyon Entrance$"

gMapSecName_SevaultCanyon::
	.string "Sevault Canyon$"

gMapSecName_TanobyRuins::
	.string "Tanoby Ruins$"

gMapSecName_SeviiIsle22::
	.string "Sevii Isle 22$"

gMapSecName_SeviiIsle23::
	.string "Sevii Isle 23$"

gMapSecName_SeviiIsle24::
	.string "Sevii Isle 24$"

gMapSecName_NavelRock::
	.string "Navel Rock$"

gMapSecName_MtEmber::
	.string "Mt. Ember$"

gMapSecName_BerryForest::
	.string "Berry Forest$"

gMapSecName_IcefallCave::
	.string "Icefall Cave$"

gMapSecName_RocketWarehouse::
	.string "Rocket Warehouse$"

gMapSecName_TrainerTower_2::
	.string "Trainer Tower$"

gMapSecName_DottedHole::
	.string "Dotted Hole$"

gMapSecName_LostCave::
	.string "Lost Cave$"

gMapSecName_PatternBush::
	.string "Pattern Bush$"

gMapSecName_AlteringCave::
	.string "Altering Cave$"

gMapSecName_TanobyChambers::
	.string "Tanoby Chambers$"

gMapSecName_ThreeIslePath::
	.string "Three Isle Path$"

gMapSecName_TanobyKey::
	.string "Tanoby Key$"

gMapSecName_BirthIsland::
	.string "Birch Island$"

gMapSecName_MoneanChamber::
	.string "Monean Chamber$"

gMapSecName_LiptooChamber::
	.string "Liptoo Chamber$"

gMapSecName_WeepthChamber::
	.string "Weepth Chamber$"

gMapSecName_DilfordChamber::
	.string "Dilford Chamber$"

gMapSecName_ScufibChamber::
	.string "Scufib Chamber$"

gMapSecName_RixyChamber::
	.string "Rixy Chamber$"

gMapSecName_ViapoisChamber::
	.string "Viapois Chamber$"

gMapSecName_EmberSpa::
	.string "Ember Spa$"

gMapSecName_CeladonDept::
	.string "Celadon Dept.$"

