gUnknown_818329D:: @ 818329D
    .string "Hi!\n"
    .string "I work at a Pokémon Mart.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in Viridian City.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

gUnknown_8183347:: @ 8183347
    .string "Please come see us if you need\n"
    .string "Poké Balls for catching Pokémon.$"

gUnknown_8183387:: @ 8183387
    .string "{PLAYER} put the Potion away in\n"
    .string "the Bag's Items Pocket.$"

gUnknown_81833B9:: @ 81833B9
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to Pallet Town\n"
    .string "quicker that way.$"

gUnknown_818343A:: @ 818343A
    .string "Route 1\n"
    .string "Pallet Town - Viridian City$"

