gUnknown_819021A:: @ 819021A
    .string "Hey!\n"
    .string "You came from Pallet Town?$"

gUnknown_819023A:: @ 819023A
    .string "You know Prof. Oak, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

gUnknown_8190289:: @ 8190289
    .string "{PLAYER} received Oak's Parcel\n"
    .string "from the Pokémon Mart clerk.$"

Text_1902BF:: @ 81902BF
    .string "Okay, thanks! Please say hi to\n"
    .string "Prof. Oak for me, too.$"

gUnknown_81902F5:: @ 81902F5
    .string "This shop does good business in\n"
    .string "antidotes, I've heard.$"

gUnknown_819032C:: @ 819032C
    .string "I've got to buy some potions.\p"
    .string "You never know when your Pokémon\n"
    .string "will need quick healing.$"

