Text_17D72C:: @ 817D72C
    .string "Oak: Hey! Wait!\n"
    .string "Don't go out!$"

gUnknown_817D74A:: @ 817D74A
    .string "Oak: It's unsafe!\n"
    .string "Wild Pokémon live in tall grass!\p"
    .string "You need your own Pokémon for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

gUnknown_817D7C8:: @ 817D7C8
    .string "I'm raising Pokémon, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

gUnknown_817D80D:: @ 817D80D
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and Pokémon as data via PC.$"

gUnknown_817D866:: @ 817D866
    .string "Oak Pokémon Research Laboratory$"

gUnknown_817D87F:: @ 817D87F
    .string "{PLAYER}'s house$"

gUnknown_817D88A:: @ 817D88A
    .string "{RIVAL}'s house$"

gUnknown_817D895:: @ 817D895
    .string "Pallet Town\n"
    .string "Shades of your journey await!$"

gUnknown_817D8BF:: @ 817D8BF
    .string "Oak: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "Pokédex?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

gUnknown_817D925:: @ 817D925
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

gUnknown_817D9AA:: @ 817D9AA
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

gUnknown_817DA16:: @ 817DA16
    .string "Oak: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

